SELECT
    COALESCE (ST.DESCRIPTION, 'TOTAL') AS SPECIALIST ,
    DATE_FORMAT(A.APPOINTMENT , '%m-%Y') AS MONTH,
    COUNT (A.ID) AS TOTAL_APPOINTMENTS
FROM
    STAFF_TYPE ST
JOIN STAFF S ON
    ST.ID = S.STAFF_TYPE
JOIN APPOINTMENTS A ON
    S.ID = A.STAFF_ID
WHERE
    ST.SPECIALIST = 'y'
    AND DATE_FORMAT(A.APPOINTMENT , '%Y') = '2021'
GROUP BY
    ST.DESCRIPTION,
    DATE_FORMAT(A.APPOINTMENT , '%m-%Y') WITH ROLLUP;