SELECT
	count (A.ID)
FROM
	STAFF_TYPE ST
JOIN STAFF S ON
	ST.ID = S.STAFF_TYPE
JOIN APPOINTMENTS A ON
    S.ID = A.STAFF_ID
   where ST.SPECIALIST = 'y'
  AND DATE_FORMAT(A.APPOINTMENT , '%Y') = '2021';
 
 SELECT
	S.FIRSTNAME ,
	ST.DESCRIPTION ,
	A.APPOINTMENT 
FROM
	STAFF_TYPE ST
JOIN STAFF S ON
	ST.ID = S.STAFF_TYPE
JOIN APPOINTMENTS A ON
    S.ID = A.STAFF_ID
   where ST.SPECIALIST = 'y'
   AND ST.DESCRIPTION LIKE 'CARDIO%'
  AND DATE_FORMAT(A.APPOINTMENT , '%Y') = '2021';

 
  SELECT
	S.FIRSTNAME ,
	S.ID ,
	ST.DESCRIPTION,
	ST.SPECIALIST 
FROM
	STAFF_TYPE ST
JOIN STAFF S ON
	ST.ID = S.STAFF_TYPE
   where ST.SPECIALIST = 'y';
 